name: SonarCloud Python

on:
  push:
    branches: ['**']    # analiza todas las ramas
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.PROYK }}
      SONAR_ORG: ${{ secrets.ORG }}

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage sonar-scanner

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover
          coverage xml

      - name: SonarCloud Scan (wait for Quality Gate)
        run: |
          sonar-scanner \
            -Dsonar.projectKey="${{ env.SONAR_PROJECT_KEY }}" \
            -Dsonar.organization="${{ env.SONAR_ORG }}" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login="${{ env.SONAR_TOKEN }}" \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.qualitygate.timeout=600 \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.projectBaseDir="${{ github.workspace }}"

